spring:
  application:
    name: config-client
  cloud:
    config:
      label: main
      profile: dev
      uri: http://localhost:8888/
      discovery:
        #是从配置中心读取文件
        enabled: true
        #配置中心的servieId，即服务名。
        serviceId: config-server
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

server:
  port: 8882

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/
